/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const __dirname: typeof import('../config/path')['__dirname']
  const appName: typeof import('../config/index')['appName']
  const appUserData: typeof import('../config/path')['appUserData']
  const dataPath: typeof import('../config/path')['dataPath']
  const getLogConfig: typeof import('../config/logger')['getLogConfig']
  const getLogPath: typeof import('../config/logger')['getLogPath']
  const isDev: typeof import('../config/env')['isDev']
  const liu: typeof import('../config/path')['liu']
}
